### PR TITLE
Frontmatter

### LINKED ISSUE #2: test fails in R CMD-check but not locally: `rmd_to_md()` writes figures to a directory
The "`rmd_to_md()` writes figures to a directory" test fails. See:
- [r code](https://github.com/b-cubed-eu/b3doc/blob/389f3923d01207f985c068fdc8a4d7095698373b/tests/testthat/test-rmd_to_md.R#L21)
- [failing test](https://github.com/b-cubed-eu/b3doc/actions/runs/13588799765/job/37989647444)

It works when I run it local, but the R CMD-check fails. 
It seems that the figures are not written at all.

### PR DESCRIPTION
**Pull request by sannegovaert**
## Tests

fix #2 

Initial test failures occurred due to the use of an R Markdown file from the gcube package, which depends on packages not loaded in b3doc.

To address this, I initially implemented the `install_required_packages()` function. This function installs or updates packages referenced within an R Markdown file through `library()` and `require()` calls. However, the tests continued to fail.

As a result, I created a **simplified example .Rmd file that relies solely on base R**, to use in the tests.

## frontmatter

`update_frontmatter()` now allows to adjust the title on top of the page and the sidebar label seperately.

### CODE REVIEW

File: R/rmd_to_md.R [hunk 1]
```diff
@@ -11,22 +11,31 @@
 #' @param fig_url_dir URL path that will be used to link to the figures in the
 #'   markdown output.
 #' @param order Order of the article in the menu.
+#' @param title Title of the article, to show in the menu.
```
Comment (peterdesmet) [inline R/rmd_to_md.R:14]: Does this set:

- `title`: what appears at the top of the page
- or `sidebar.label`: what appears in the navigation on the left?

If the latter, then I would:

- rename to `sidebar_label`
- rename `order` to `sidebar_order`
- Switch params, so `sidebar_label` is first (cf. [Stardocs](https://starlight.astro.build/reference/frontmatter/#sidebarconfig) doc)

File: R/update_frontmatter.R [hunk 2]
```diff
@@ -5,17 +5,23 @@
 #' @param md_file_path Path to the markdown file on disk.
 #' @param rmd_file Path to the R Markdown file, either a local path or a URL.
 #' @param order Number indicating the order of the article in the menu.
+#' @param title Title of the article, to show in the menu.
```
Comment (peterdesmet) [inline R/update_frontmatter.R:8]: Same comment as above.

**Review by peterdesmet — CHANGES_REQUESTED** [review]
Nice! Excellent idea to use a base-R example.Rmd! Does it also generate an image for the plot?

- See my comment regarding the params. Note: I would use `inheritParams` to avoid repetition.
- I would remove `install_required_packages()` if we don't plan to use it.

Let's make the changes and see how test-coverage responds.

**Comment by sannegovaert** [comment]
> Nice! Excellent idea to use a base-R example.Rmd! Does it also generate an image for the plot?

Yes it does :-)

**Comment by peterdesmet** [comment]
Would it make sense to work with `_snaps` for the test or is that not worth it?

**Comment by sannegovaert** [comment]
> Would it make sense to work with `_snaps` for the test or is that not worth it?

The problem with the snapshot is that the directory of the image changes with every test run. Do you know how to solve this?

image

**Comment by peterdesmet** [comment]
Variations in snapshot file solved as follows:

- For `fig_url_dir` I used a fixed value `"/software/example/"`
- For lastUpdated, I used the `expect_snapshot_file` [parameter](https://testthat.r-lib.org/reference/expect_snapshot_file.html#arguments) `transform` to convert the date to the literal value `<current_date>`.

I also updated the function examples and bundled some of the tests.

File: tests/testthat/test-rmd_to_md.R [hunk 3]
```diff
@@ -1,100 +1,69 @@
...
+  on.exit(unlink(temp_dir, recursive = TRUE))
+  expected_md_dir <- file.path(temp_dir, "src/content/docs/software/example")
+  expected_fig_dir <- file.path(temp_dir, "public/software/example")
+
+  rmd_to_md(
+    rmd_file = testthat::test_path("example.Rmd"),
+    md_dir = expected_md_dir,
+    fig_dir = expected_fig_dir,
+    fig_url_dir = "/software/example/",
+    sidebar_order = 2
```
Comment (peterdesmet) [inline tests/testthat/test-rmd_to_md.R:17]: Please remove this line (and comma above) once `sidebar_order` is no longer required.

File: tests/testthat/test-rmd_to_md.R [hunk 4]
```diff
@@ -1,100 +1,69 @@
...
   original_opts_knit <- knitr::opts_knit$get()
 
-  rmd_to_md(rmd_file, md_dir, fig_dir, fig_url_dir, order)
-
+  rmd_to_md(
+    rmd_file = testthat::test_path("example.Rmd"),
+    md_dir = file.path(temp_dir, "src/content/docs/software/example"),
+    fig_dir = file.path(temp_dir, "public/software/example"),
+    fig_url_dir = "/software/example/",
+    sidebar_order = 2
```
Comment (peterdesmet) [inline tests/testthat/test-rmd_to_md.R:64]: Please remove this line (and comma above) once `sidebar_order` is no longer required.

**Review by peterdesmet — CHANGES_REQUESTED** [review]
Cool functionality! Please update the handling of `sidebar_order`.

- Should be an integer
- Should be optional, as in: it is not set in frontmatter if not provided

**Comment by sannegovaert** [comment]
Thanks!
I applied the changes.

File: tests/testthat/_snaps/rmd_to_md/example.md [hunk 5]
```diff
@@ -0,0 +1,129 @@
+---
+title: Custom title
+author: Sanne Govaert
+date: '<current_date>'
+output: html_document
+lastUpdated: <current_date>
+sidebar:
+  label: Custom sidebar label
+  order: 2
+
```
Comment (peterdesmet) [inline tests/testthat/_snaps/rmd_to_md/example.md:10]: @sannegovaert do you think this empty line can be avoided?

**Review by peterdesmet — APPROVED** [review]
Great! One remaining (optional) comment regarding making frontmatter prettier.
